### ISSUE TITLE
ImportError: cannot import name 'Metric' from 'vicinity.datatypes'

### ISSUE THREAD

**Issue by 821711614** [MinishLab/vicinity#35]

**Comment by Pringled** [comment]
Hi @821711614, thanks for raising this. It seems that the readme was outdated, I've updated it. I also noticed a small bug in passing metrics to basic backend which I've just released a fix for in https://github.com/MinishLab/vicinity/releases/tag/v0.3.1. Let me know if you encounter any other issues!

**Comment by Pringled** [comment]
Closing this as this is fixed in the newest release. Feel free to open a new issue if you do encounter any more problems!
